---
output:
  html_document: default
  pdf_document: 
    latex_engine: xelatex
  word_document: default
---
# Anna Oskina
NLP Data Scientist

<div id="webaddress">
<a href="annaoskina@gmail.com">annaoskina@gmail.com</a>
| <a href="https://github.com/annaoskina">My GitHub page</a>
</div>


## Currently

Guest contributor for Japanese Study in <a href="https://digitalorientalist.com/">The Digital Orientalist </a>

### Specialized in

Japanese study, Digital Humanities


### Research interests

DH, Japanese text mining, data analysis, TF-IDF, topic modeling, stylometry, network analysis, text encoding initiative (TEI)


## Education

`2019-2022`
__MA, Digital Humanities, National Research University 'Higher School of Economics', Moscow, Russia.__

`2006-2011`
__Specialist degree, Russian State University for the Humanities, Moscow, Russia.__


## Workshops and scholarships

`June 2022`
__"Japanese Language Text Mining”, Digital Humanities Methods for Japanese Studies, University of Chicago, Chicago, USA.__

`February 2019`
__EAJRS/NIJL Kuzushi-ji Workshop 2019, Collège de France, Paris, France.__

`August 2018`
__Fifth Graduate Summer School in Japanese Early-modern Palaeography, Emmanuel College, Cambridge, UK.__

`2009-2010`
__Monbukagakusho student at Chiba Univesrity, Chiba, Japan.__


## Occupation

`2022-now`
__Guest contributor for Japanese Study in The Digital Orientalist (remote, part-time)__ 

`2011-2022`
__Lecturer at National Research University 'Higher School of Economics', Moscow, Russia.__ 
<a href="https://www.hse.ru/en/staff/annaoskina">https://www.hse.ru/en/staff/annaoskina</a>

Courses:

* Contemporary Japanese
* Classical Japanese
* Japanese literature


## Awards

`2019`
Best Teacher - 2019, HSE University, Moscow.


## Publications

`Article` Oskina A., Pasivkina S. The Precious Notes on Papermaking» (“Kamisuki Cho:ho:ki”) as the first illustrated Guide to Papermaking // Japanese Studies in Russia, 2018. № 3. Pp. 49-77. (in Russian)


`Article` Oskina A. Two Diaries of the Nun Abutsu (1221?-1283): Literature, Biography, Personality.// RGGU Bulletin. History. Philology. Cultural Studies. Oriental Studies. 2018. № 12 (45). Pp. 251-269. (in Russian)


`Chapter` Oskina A. Illustrated book "Ehon Hanakazura" // Survival and Sustainability: Contemporary Studies in Humanities 2 Issue 314. Chiba University, 2017. Chapter. 3. Pp. 56-72. (in Russian and Japanese)


`Chapter` Oskina A. Illustrated book "Ehon Hanakazura" (1765): Education Books in the Edo Period // History and Culure of Traditional Japan 10. Orientalia et Classica. Volume LXIX. St.Petersburg: Hyperion, 2017. Pp. 176-195. (in Russian)


`Chapter` Oskina A. Motives and Intentions of the Authors in Diaries Based on "The Diary of the Waning Moon" by the Nun Abutsu and "The Notes" by Princess Dashkova // Literature and History: Representation and Narrative Issue 289. Chiba University, 2015. Pp. 83-99. (in Russian)


`Article` Oskina A. "The Diary of the Waning Moon": Content, Composition, Style // Vestnik Novosibirsk State University: History and Philology. 2014. Vol. 13. № 4. Pp. 153-158. (in Russian)


`Chapter` Oskina A. Distinctive features of "The Diary of the Waning Moon" by the Nun Abutsu (1221?-1283) // Oriental Societies: Traditions and Modernity. Moscow, Baku: Center for Strategic Studies under the President of Azerbaijan, 2014. Pp. 328-342. (in Russian)


`Chapter` Oskina A. 高等女学校の日常生活：女学生の楽しみや悩み　//　アルザス日欧知的交流事業　日本研究セミナー［大正／戦前］報告書. Strasbourg : Centre européen d’études japonaises d’Alsace, 2014. (in Japanese)


`Article` Oskina A. Kaibara Ekken and his "Precepts for girls" // Japan. Annuary. 2013. Pp. 198-215. (in Russian)


## Conferences

`2022` 23th Annual Conference "History and Culture of Japan" (Moscow). Presentation: Semantic Analysis of Loanwords Graphics in Fiction of the Meiji-Taisho Periods.


`2022` EADH2021 (Krasnoyarsk). Presentation: Parents and Children in Russian Drama.


`2019` 21th Annual Conference "History and Culture of Japan" (Moscow). Presentation: Travel notes of the Nun Abutsu: connection with the literary tradition.


`2018`  20th Annual Conference "History and Culture of Japan" (Moscow). Presentation: The History of the Reizei Family Library.


`2017`  19th Annual Conference "History and Culture of Japan" (Moscow). Presentation: Education with a book in the Edo Period based on "Ehon Hanakazura" (1765).


`2014`  16th Annual Conference "History and Culture of Japan" (Moscow). Presentation: Prose and poetry in the nun Abutsu's (1221?-1283) "The Diary of the Waning Moon".


`2013`  15th Annual Conference "History and Culture of Japan" (Moscow). Presentation: The nun Abutsu and "The Tale of Genji".


Written Monuments of the East. The Problems of Interpretation and Translation (Moscow). Presentation: The problems in translation of "Izayoi nikki" by the nun Abutsu: quotes and allusions.


European Association of Japanese Resource Specialists Conference 2013 (Paris). Presentation: Illustrated book "Ehon hanakazura" (1765): pictures, poems, proverbs.


2nd Congress of Young Orientalists of Russia and the CIS (Baku). Presentation: Distinctive features of "The Diary of the Waning Moon" by the nun Abutsu (1221?-1283).


`2012`  14th Annual Conference "History and Culture of Japan" (Moscow). Presentation: From capital to capital: the travelling in Heian and Edo periods.


Nikolai Nevsky Memorial Conference - International Symposium in Honor of the 120th Birthday of N.A. Nevsky (St. Petersburg). Presentation: The diaries of the nun Abutsu as a source for her biography.


`2011`
13th Annual Conference "History and Culture of Japan" (Moscow). Presentation: "The Great Learning for women": from Kaibara Ekken to Fukuzawa Yukichi.


Japanese Study Seminar - Taisho Prewar (Showa) (Alsace). Presentation: Everyday Life in Women High Schools in the Taisho period.


`2010`
Conference of Young Japanologists (St. Petersburg). Presentation: Kaibara Ekken and Fukuzawa Yukichi: old and new views on women education.


`2009`
11th Annual Conference "History and Culture of Japan" (Moscow). Presentation: Kaibara Ekken and women learning in the Edo period.


<!-- ### Footer

Last updated: July 2022 -->

